pipeline {
  agent none
  stages {
    stage('Back-end') {
      steps {
        sh 'echo $USER'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
